version: '3.8'

services:

  ueransim-gnb11:
    container_name: ueransim-gnb11
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slicle1/ue11cfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb.free5gc.org


  ueransim-gnb21:
    container_name: ueransim-gnb21
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/slice2/gnb21cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice2/ue21cfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb2.free5gc.org

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
